services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: bess_finder
      POSTGRES_USER: bess
      POSTGRES_PASSWORD: bess_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
